---
title: "Visualizing Society: Class Notes"
author: "Ben Wallace"
date: "1/12/2022"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
description: "This is my notebook for SOCIOL 232 at Duke University"
---
---
title: "Visualizing Society: Class Notes"
author: "Ben Wallace"
date: "1/12/2022"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
description: "This is my notebook for SOCIOL 232 at Duke University"
---
# Class Notes: Visualizing Society {-}

<!--chapter:end:index.Rmd-->


# January 12, Learning R

Placeholder


### What R looks like
### Everything in R has a name
### Do things to objects with a function
### Types and classes
### First plots

<!--chapter:end:01-learningR.Rmd-->


# January 19, Ways of Seeing

Placeholder


### Berger and Renaissance Art
### Visual Literacy of Quantitative Data

<!--chapter:end:02-seeing.Rmd-->


# Making Graphs

Placeholder


### What exactly is a graph anyway?
### How ggplot works: The flow of action
## January 26, Making Graphs (Continuation)
### Mapping vs. setting aesthetics
### Palmer Penguins and Simpson's Paradox
### Grouped data and group aesthetic

<!--chapter:end:03-graphs.Rmd-->


# Vision Data and Design

Placeholder


## Smoothers
## Bad taste, bad data, and bad perception
### Bad taste
### Bad data
### Bad perception
#### Edges and contrasts
#### Color
#### Pre-attentive processing
## Gestalt inferences

<!--chapter:end:04-visiondata.Rmd-->


# Textual Analysis

Placeholder


## Gutenberg data
## Tidydata
## Saving your Work

<!--chapter:end:05-textualanalysis.Rmd-->


# Tidy Data

Placeholder


## Counts are easy
## Transform data first if dealing with proportions or other summary statistics
### `group_by()`
### `filter()` and `select()`
### `Mutate()`
### `Summarize()`
## GSS Data example
### Objects in pipeline carry forward assumptions
### Shorthand version
### Pipeline tables are easier to check for errors
### GSS Graph
## Other forms of facetting
### Facetting multiple variables
### Facet grid
## The Process
## Organ Data

<!--chapter:end:06-tidy.Rmd-->

# What is Data

Sports are a "model organism" of social science. The rules provide a rigid and episodic but still socially real model of human behavior.

Random: Use `glue` package to add color to the titles and other labels.

## History of Data

There is a relationship between the history of data and the development of *markets* and the *state*.

Categories used in data both reflect and express historically-contingent social formations.

- Categories from North Carolina's 1790 census sets up the hierarchy from free white males to slaves.

  - Later focus on how to categorize people who interracial through langauge of "Mulatto, Quadroom, Octoroon..." during Jim Crow.

There are three broad ideas about the relationships between categories and the what we think of as the world or reality.

- "Carving nature at the joints," trying to see what the world *objectively* looks like.

- Process of data collection is subjective (e.g. American vs. French beef cuts).

- Realists argue that there is an objective and subjective experience; purpose of science to approximate objectivity.

Categories should be exclusive and exhaustive (i.e. observations cannot belong to more than one category and every observation should fit a category).




<!--chapter:end:07-data.Rmd-->


# Pandemic Data

Placeholder


## Vegetable Fat and Animal Fat Plot
## COVID-19
### `dplyr`'s window functions
### Patchwork
## Organ Data

<!--chapter:end:08-pandemic.Rmd-->


# Class Notes: Visualizing Society {-}

Placeholder


### What R looks like
### Everything in R has a name
### Do things to objects with a function
### Types and classes
### First plots
### Berger and Renaissance Art
### Visual Literacy of Quantitative Data
### What exactly is a graph anyway?
### How ggplot works: The flow of action
## January 26, Making Graphs (Continuation)
### Mapping vs. setting aesthetics
### Palmer Penguins and Simpson's Paradox
### Grouped data and group aesthetic
## Smoothers
## Bad taste, bad data, and bad perception
### Bad taste
### Bad data
### Bad perception
#### Edges and contrasts
#### Color
#### Pre-attentive processing
## Gestalt inferences
## Gutenberg data
## Tidydata
## Saving your Work
## Counts are easy
## Transform data first if dealing with proportions or other summary statistics
### `group_by()`
### `filter()` and `select()`
### `Mutate()`
### `Summarize()`
## GSS Data example
### Objects in pipeline carry forward assumptions
### Shorthand version
### Pipeline tables are easier to check for errors
### GSS Graph
## Other forms of facetting
### Facetting multiple variables
### Facet grid
## The Process
## Organ Data
## History of Data
### Vegetable Fat and Animal Fat Plot
### COVID-19
#### `dplyr`'s window functions
#### Patchwork

<!--chapter:end:notes-output.Rmd-->

